//! Minimal build script that copies pre-generated artifacts into `$OUT_DIR`
//! for embedding into the binary.
//!
//! `cx.lock` is generated by `cargo run -p pronto-build -- prepare` (which
//! extracts it from pixi.lock and applies exclude filters). When
//! `PRONTO_EMBED_BUNDLE=1`, `payload.tar.zst` must be pre-generated by
//! `cargo run -p pronto-build -- bundle`.

use std::{env, path::PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed=cx.lock");
    println!("cargo:rerun-if-changed=cx.lock.hash");
    println!("cargo:rerun-if-changed=payload.tar.zst");
    println!("cargo:rerun-if-env-changed=PRONTO_EMBED_BUNDLE");
    println!("cargo:rerun-if-env-changed=CX_EMBED_PAYLOAD");
    println!("cargo:rerun-if-env-changed=CX_INSTALL_METHOD");

    let cx_lock_src = manifest_dir.join("cx.lock");
    let cx_lock_dst = out_dir.join("cx.lock");
    assert!(
        cx_lock_src.exists(),
        "cx.lock not found — run `cargo run -p pronto-build -- prepare` first"
    );
    std::fs::copy(&cx_lock_src, &cx_lock_dst).expect("failed to copy cx.lock to OUT_DIR");

    let payload_dst = out_dir.join("payload.tar.zst");
    let embed_bundle = env_flag("PRONTO_EMBED_BUNDLE") || env_flag("CX_EMBED_PAYLOAD");

    if embed_bundle {
        let payload_src = manifest_dir.join("payload.tar.zst");
        assert!(
            payload_src.exists(),
            "PRONTO_EMBED_BUNDLE=1 but payload.tar.zst not found — \
             run `cargo run -p pronto-build -- bundle` first"
        );
        std::fs::copy(&payload_src, &payload_dst).expect("failed to copy payload.tar.zst");
    } else if !payload_dst.exists() {
        std::fs::write(&payload_dst, b"").expect("failed to write empty payload.tar.zst");
    }
}

fn env_flag(name: &str) -> bool {
    env::var(name)
        .ok()
        .is_some_and(|v| matches!(v.as_str(), "1" | "true" | "TRUE" | "yes" | "YES"))
}
