//! Minimal build script that copies pre-generated artifacts into `$OUT_DIR`
//! for embedding into the binary.
//!
//! `artifact.lock` is generated by `cargo run -p pronto -- lock` (which
//! extracts it from pixi.lock and applies exclude filters). When
//! `PRONTO_EMBED_BUNDLE=1`, `bundle.tar.zst` must be pre-generated by
//! `cargo run -p pronto -- bundle`.

use std::{env, path::PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed=artifact.lock");
    println!("cargo:rerun-if-changed=artifact.lock.hash");
    println!("cargo:rerun-if-changed=bundle.tar.zst");
    println!("cargo:rerun-if-env-changed=PRONTO_EMBED_BUNDLE");
    println!("cargo:rerun-if-env-changed=CX_INSTALL_METHOD");

    let artifact_lock_src = manifest_dir.join("artifact.lock");
    let artifact_lock_dst = out_dir.join("artifact.lock");
    assert!(
        artifact_lock_src.exists(),
        "artifact.lock not found — run `cargo run -p pronto -- lock` first"
    );
    std::fs::copy(&artifact_lock_src, &artifact_lock_dst)
        .expect("failed to copy artifact.lock to OUT_DIR");

    let bundle_dst = out_dir.join("bundle.tar.zst");
    let embed_bundle = env_flag("PRONTO_EMBED_BUNDLE");

    if embed_bundle {
        let bundle_src = manifest_dir.join("bundle.tar.zst");
        assert!(
            bundle_src.exists(),
            "PRONTO_EMBED_BUNDLE=1 but bundle.tar.zst not found — \
             run `cargo run -p pronto -- bundle` first"
        );
        std::fs::copy(&bundle_src, &bundle_dst).expect("failed to copy bundle.tar.zst");
    } else if !bundle_dst.exists() {
        std::fs::write(&bundle_dst, b"").expect("failed to write empty bundle.tar.zst");
    }
}

fn env_flag(name: &str) -> bool {
    env::var(name)
        .ok()
        .is_some_and(|v| matches!(v.as_str(), "1" | "true" | "TRUE" | "yes" | "YES"))
}
